<a href="https://colab.research.google.com/github/Maf18z1/II1/blob/II/Chekalov_A_Workbook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.

Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:

 pip install numpy

Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:

 import numpy as np

Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.

Наиболее важные атрибуты объектов ndarray:

ndarray.ndim - число измерений (чаще их называют "оси") массива.

ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.

ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.

ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.

ndarray.itemsize - размер каждого элемента массива в байтах.

ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html

1.2.1 Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [1]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Задача:
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.


In [2]:
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Задача:
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [3]:
z=np.random.random((10,10))
zmin,zmax,zmean=z.min(),z.max(),z.mean()
print(zmin,zmax,zmean)

0.0004692757624989996 0.9925595119235147 0.45489831369111355


1.2.4 Задача:
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.


In [6]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Задача:
Выяснить результат следующих выражений:

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1

In [7]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


1.2.6 Задача:
Отсортировать массив.


In [8]:
arr=np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [9]:
arr = np.full(64, 0).reshape(8, 8)
for i in range(8):
    if i % 2 == 0:
        arr[i][1:8:2] = 1
    else:
        arr[i][0:8:2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [19]:
arr = np.arange(25).reshape(5, 5)
for i in range(1, 5):
    arr[i] = arr[0]

print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задача:
Создать массив 3x3x3 со случайными значениями.

In [22]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.47553332 0.04320719 0.03491356]
  [0.62252108 0.91659825 0.13176727]
  [0.81321003 0.63304614 0.34074858]]

 [[0.150493   0.82550536 0.86766118]
  [0.53924307 0.77766042 0.6090552 ]
  [0.69249926 0.5773809  0.04015466]]

 [[0.66652938 0.75080616 0.33190979]
  [0.17609804 0.66093943 0.13739766]
  [0.75766233 0.29252287 0.587727  ]]]


1.3.4 Задача:
Создать матрицу с 0 внутри, и 1 на границах.


In [24]:
size = 5
arr = np.full(size*size, 0).reshape(size, size)

for i in range(size):
    if i == 0 or i == size-1:
        arr[i] = np.full(size, 1)
        continue
    arr[i][0], arr[i][size-1] = 1, 1

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


1.3.5 Задача:
Создайте массив и отсортируйте его по убыванию.

In [29]:
arr = np.random.random(5)
print(np.sort(arr)[::-1])

[0.35616644 0.04675203 0.0412286  0.0169782  0.00938009]


1.3.6 Задача:
Создайте матрицу, выведите ее форму, размер и размерность.

In [33]:
arr = np.random.random((2, 2, 2))
print(arr,arr.shape)

[[[0.22940903 0.43870236]
  [0.32263528 0.19769662]]

 [[0.0012834  0.45948664]
  [0.90705044 0.5839121 ]]] (2, 2, 2)


Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких
источников.

Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:

 pip install pandas

Для импорта библиотеки используйте команду:

import pandas as pd

Библиотека pandas предоставляет две ключевые структуры данных:

Series и DataFrame.

Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.

DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.

2.2.1 Задача:
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [34]:
import pandas as pd

lst = [1, 2, 3, 4, 5]
d = {'a':1,'b':2,'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr)

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64


2.2.2 Задача:
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [35]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a','b','c','d','e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Задача:
Создайте новый фрейм данных.

In [38]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Задача:
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [ ]:
url = ' https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

2.2.5 Задача:
Пронализировать характеристики фрейма данных.

In [43]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Возраст
count   2.000000
mean   31.500000
std     9.192388
min    25.000000
25%    28.250000
50%    31.500000
75%    34.750000
max    38.000000

2.2.6 Задача:
Выберите индивидуальные данные или срезы фрейма данных.


In [51]:
dataframe.iloc[1:4]

Имя  Возраст  Водитель
1  Стивен Стивенсон       25     False

2.2.7 Задача:
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [ ]:
dataframe[dataframe['PClass'] == '1st'].head(2)

2.3.1 Задача:
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [60]:
a = pd.Series([1, 2, 3])
b = pd.Series([4, 7, 6])
print(sum((a-b)**2)**0.5)

6.557438524302


2.3.2 Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
url = 'https://github.com/akmand/datasets/blob/main/german.csv'

dataframe = pd.read_csv(url)
dataframe.head(5)
dataframe