<a href="https://colab.research.google.com/github/Maf18z1/II1/blob/II/Chekalov_A_Workbook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.

Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:

 pip install numpy

Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:

 import numpy as np

Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.

Наиболее важные атрибуты объектов ndarray:

ndarray.ndim - число измерений (чаще их называют "оси") массива.

ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.

ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.

ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.

ndarray.itemsize - размер каждого элемента массива в байтах.

ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html

1.2.1 Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [ ]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Задача:
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.


In [ ]:
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Задача:
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [ ]:
z=np.random.random((10,10))
zmin,zmax,zmean=z.min(),z.max(),z.mean()
print(zmin,zmax,zmean)

0.0004692757624989996 0.9925595119235147 0.45489831369111355


1.2.4 Задача:
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.


In [ ]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Задача:
Выяснить результат следующих выражений:

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


1.2.6 Задача:
Отсортировать массив.


In [ ]:
arr=np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
arr = np.full(64, 0).reshape(8, 8)
for i in range(8):
    if i % 2 == 0:
        arr[i][1:8:2] = 1
    else:
        arr[i][0:8:2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
arr = np.arange(25).reshape(5, 5)
for i in range(1, 5):
    arr[i] = arr[0]

print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задача:
Создать массив 3x3x3 со случайными значениями.

In [1]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.75798998 0.66861724 0.17823595]
  [0.70893154 0.53439928 0.4829452 ]
  [0.0781479  0.67011932 0.47743272]]

 [[0.66145351 0.55459736 0.82072996]
  [0.10341916 0.41609004 0.77764306]
  [0.19566599 0.25580999 0.12919031]]

 [[0.11362088 0.76579929 0.60446703]
  [0.60545915 0.23408383 0.25724926]
  [0.30931288 0.41599025 0.15784111]]]


1.3.4 Задача:
Создать матрицу с 0 внутри, и 1 на границах.


In [ ]:
size = 5
arr = np.full(size*size, 0).reshape(size, size)

for i in range(size):
    if i == 0 or i == size-1:
        arr[i] = np.full(size, 1)
        continue
    arr[i][0], arr[i][size-1] = 1, 1

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


1.3.5 Задача:
Создайте массив и отсортируйте его по убыванию.

In [ ]:
arr = np.random.random(5)
print(np.sort(arr)[::-1])

[0.35616644 0.04675203 0.0412286  0.0169782  0.00938009]


1.3.6 Задача:
Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
arr = np.random.random((2, 2, 2))
print(arr,arr.shape)

[[[0.22940903 0.43870236]
  [0.32263528 0.19769662]]

 [[0.0012834  0.45948664]
  [0.90705044 0.5839121 ]]] (2, 2, 2)


Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких
источников.

Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:

 pip install pandas

Для импорта библиотеки используйте команду:

import pandas as pd

Библиотека pandas предоставляет две ключевые структуры данных:

Series и DataFrame.

Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.

DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.

2.2.1 Задача:
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [ ]:
import pandas as pd

lst = [1, 2, 3, 4, 5]
d = {'a':1,'b':2,'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr)

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64


2.2.2 Задача:
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a','b','c','d','e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Задача:
Создайте новый фрейм данных.

In [ ]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Задача:
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [25]:
url = 'https://raw.githubusercontent.com/Pozdniakov/tidy_stats/master/data/heroes_information.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Unnamed: 0         name Gender Eye color               Race Hair color  \
0           0       A-Bomb   Male    yellow              Human    No Hair   
1           1   Abe Sapien   Male      blue      Icthyo Sapien    No Hair   
2           2     Abin Sur   Male      blue            Ungaran    No Hair   
3           3  Abomination   Male     green  Human / Radiation    No Hair   
4           4      Abraxas   Male      blue      Cosmic Entity      Black   

   Height          Publisher Skin color Alignment  Weight  
0   203.0      Marvel Comics          -      good   441.0  
1   191.0  Dark Horse Comics       blue      good    65.0  
2   185.0          DC Comics        red      good    90.0  
3   203.0      Marvel Comics          -       bad   441.0  
4   -99.0      Marvel Comics          -       bad   -99.0

2.2.5 Задача:
Пронализировать характеристики фрейма данных.

In [29]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Unnamed: 0      Height      Weight
count  734.000000  734.000000  732.000000
mean   366.500000  102.254087   43.855191
std    212.031837  139.624543  130.823733
min      0.000000  -99.000000  -99.000000
25%    183.250000  -99.000000  -99.000000
50%    366.500000  175.000000   62.000000
75%    549.750000  185.000000   90.000000
max    733.000000  975.000000  900.000000

2.2.6 Задача:
Выберите индивидуальные данные или срезы фрейма данных.


In [33]:
dataframe.iloc[1:4]

Unnamed: 0         name Gender Eye color               Race Hair color  \
1           1   Abe Sapien   Male      blue      Icthyo Sapien    No Hair   
2           2     Abin Sur   Male      blue            Ungaran    No Hair   
3           3  Abomination   Male     green  Human / Radiation    No Hair   

   Height          Publisher Skin color Alignment  Weight  
1   191.0  Dark Horse Comics       blue      good    65.0  
2   185.0          DC Comics        red      good    90.0  
3   203.0      Marvel Comics          -       bad   441.0

2.2.7 Задача:
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [37]:
dataframe[dataframe['Height'] > 185].head(5)

Unnamed: 0           name Gender Eye color               Race Hair color  \
0            0         A-Bomb   Male    yellow              Human    No Hair   
1            1     Abe Sapien   Male      blue      Icthyo Sapien    No Hair   
3            3    Abomination   Male     green  Human / Radiation    No Hair   
5            5  Absorbing Man   Male      blue              Human    No Hair   
10          10     Agent Zero   Male         -                  -          -   

    Height          Publisher Skin color Alignment  Weight  
0    203.0      Marvel Comics          -      good   441.0  
1    191.0  Dark Horse Comics       blue      good    65.0  
3    203.0      Marvel Comics          -       bad   441.0  
5    193.0      Marvel Comics          -       bad   122.0  
10   191.0      Marvel Comics          -      good   104.0

2.3.1 Задача:
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [38]:
a = pd.Series([1, 2, 3])
b = pd.Series([4, 7, 6])
print(sum((a-b)**2)**0.5)

6.557438524302


2.3.2 Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [40]:
url = 'https://raw.githubusercontent.com/Pozdniakov/tidy_stats/master/data/heroes_information.csv'

dataframe = pd.read_csv(url)
dataframe.head(5)

Unnamed: 0         name Gender Eye color               Race Hair color  \
0           0       A-Bomb   Male    yellow              Human    No Hair   
1           1   Abe Sapien   Male      blue      Icthyo Sapien    No Hair   
2           2     Abin Sur   Male      blue            Ungaran    No Hair   
3           3  Abomination   Male     green  Human / Radiation    No Hair   
4           4      Abraxas   Male      blue      Cosmic Entity      Black   

   Height          Publisher Skin color Alignment  Weight  
0   203.0      Marvel Comics          -      good   441.0  
1   191.0  Dark Horse Comics       blue      good    65.0  
2   185.0          DC Comics        red      good    90.0  
3   203.0      Marvel Comics          -       bad   441.0  
4   -99.0      Marvel Comics          -       bad   -99.0

2.3.3 Задача:
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [46]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['Gender'] == 'Female'].head(2)

Unnamed: 0        name  Gender Eye color    Race Hair color  Height  \
8            8    Agent 13  Female      blue       -      Blond   173.0   
24          24  Angel Dust  Female    yellow  Mutant      Black   165.0   

        Publisher Skin color Alignment  Weight  
8   Marvel Comics          -      good    61.0  
24  Marvel Comics          -      good    57.0

Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).

Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.

Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.

На практике наиболее распространены следующие методы
нормализации признаков:

- Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;

- Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.

При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

3.2.1. Задача:
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [48]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2. Задача:
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [51]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)

print(standardized)
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее: 0
Стандартное отклонение: 1.0


3.2.3. Задача:
Дан фрейм данных

dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],

 'B':[103.02,107.26,110.35,114.23,114.68],

 'C':['big','small','big','small','small']})

Необходимо масштабировать его числовые столбцы.

In [53]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                           'B':[103.02,107.26,110.35,114.23,114.68],
                           'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задача:
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [56]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url)
scale1 = preprocessing.MinMaxScaler()
scale2 = preprocessing.StandardScaler()
dataframe[['sepal_length_cm']] = scale1.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scale2.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]